# This file is part of gcal-watcher.
# http://github.com/garaemon/gcal-watcher

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2018, garaemon <garaemon@gmail.com>

language: python

python:
    - "3.4"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
